name: cpp-linter

on:
  pull_request:
    branches: [main, master, develop]
    paths: ['**.c', '**.cpp', '**.h', '**.hpp', '**.vcxproj']
  push:
    branches: [main, master, develop]
    paths: ['**.c', '**.cpp', '**.h', '**.hpp', '**.vcxproj']

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: cpp-linter/cpp-linter-action@main
        id: linter
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: ''
          tidy-checks: >
            clang-diagnostic-*,
            clang-analyzer-*,
            performance-*,
            bugprone-*,
            -bugprone-infinite-loop,
            -bugprone-branch-clone,
            readability-*,
            -readability-identifier-length,
            -readability-implicit-bool-conversion,
            -readability-isolate-declaration,
            -readability-uppercase-literal-suffix,
            modernize-*,
            -modernize-use-trailing-return-type,
            cppcoreguidelines-*,
            -cppcoreguidelines-avoid-c-arrays
          extra-args: '-std=c++20 -Wall'
          files-changed-only: true
          lines-changed-only: 'diff'
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
          step-summary: true

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed != 0
        run: |
          echo "some linter checks failed. ${{ steps.linter.outputs.checks-failed }}"
